# 0. Memote notebook

### Import libraries

In [2]:
#%pip install cobra
#%pip install memote

In [15]:
import pandas as pd
from cobra.io import read_sbml_model, write_sbml_model
from cobra import Reaction, Metabolite
from cobra.util import create_stoichiometric_matrix
import numpy as np

### Load the models

In [4]:
iJO1366 =  read_sbml_model('Data\iJO1366.xml')
iJO1366

<Model iJO1366 at 0x20ca75bcdf0>

In [9]:
iML1515 =  read_sbml_model('Data\iML1515.xml')
iML1515

<Model iML1515 at 0x20cb54395e0>

### Assess memote

We assessed two _E. coli_ models using memote. A memote analysis generates detailed reports for each model, assessing its quality and completeness.

In [5]:
#Model 1
#!memote report snapshot Data/iJO1366.xml

In [13]:
#Model 2
#!memote report snapshot Data/iML1515.xml

### Explore the model

In [13]:
# Create the stoichiometric matrix
S = create_stoichiometric_matrix(iML1515)
print(S)

[[0. 0. 0. ... 0. 0. 1.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


The stoichiometric matrix represents the relationships between different biochemical species (e.g., metabolites and reactions) in a biological system. Each element of the matrix corresponds to the stoichiometric coefficient of a metabolite in a particular reaction.

In [18]:
# Check non-zero elements of S
non_zero_elem = np.count_nonzero(S)
zero_elem = np.count_nonzero(S == 0)
percentage_non_zero = round(non_zero_elem / (zero_elem + non_zero_elem) * 100, 2)
print("The percentage of non-zero elements in iML1515 is:", str(percentage_non_zero) + "%")

The percentage of non-zero elements in iMM1515 is: 0.21%


This percentage is low, implying that the metabolic network is sparse with relatively few metabolites participating in a relatively small number of reactions compared to the total possibilities. This makes working with it more efficient, since the interactions in the model are selective and specific.